name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - hugo
  watch:
    types: [started]
  # schedule:
  #   - cron: "0 */2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "potbye@users.noreply.github.com"
          git config user.name "potbye"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.10
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.95.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: "potbye"
          user_email: "potbye@users.noreply.github.com"
          publish_dir: ./public
          publish_branch: master # deploying branch
          cname: garden.ronnapat.me
